/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.croacker.lbutil.nui;

import ru.croacker.lbutil.nui.component.ConnectionsPopupMenu;
import ru.croacker.lbutil.nui.component.connection.ConnectionPanel;
import ru.croacker.lbutil.nui.component.connectionslist.ConnectionsListPanel;
import ru.croacker.lbutil.nui.component.exp.ExportChangelogPanel;
import ru.croacker.lbutil.nui.component.imp.ImportChangelogPanel;
import ru.croacker.lbutil.ui.model.ConnectionUnitModel;

/**
 *
 * @author a_gumenyuk
 */
public class MainFrm extends javax.swing.JFrame {

  private javax.swing.JPanel jpImport;
  private javax.swing.JButton jbAddConnection;
  private javax.swing.JButton jbExport;
  private javax.swing.JButton jbImport;
  private javax.swing.JButton jbRemoveConnection;
  private javax.swing.JButton jbSelectExportFile;
  private javax.swing.JButton jbSelectImportFile;
  private javax.swing.JButton jbTestConnection;
  private javax.swing.JComboBox jcbDriver;
  private javax.swing.JList jlConnectionsList;
  private javax.swing.JLabel jlExportFile;
  private javax.swing.JLabel jlImportFile;
  private javax.swing.JLabel jlJdbcDriver;
  private javax.swing.JLabel jlPassword;
  private javax.swing.JLabel jlUrl;
  private javax.swing.JLabel jlUser;
  private javax.swing.JMenu jmFile;
  private javax.swing.JMenu jmHelp;
  private javax.swing.JMenu jmService;
  private javax.swing.JMenuBar jmbMain;
  private javax.swing.JMenuItem jmiAbout;
  private javax.swing.JMenuItem jmiExit;
  private javax.swing.JMenuItem jmiParameters;
  private javax.swing.JPanel jpConnection;
  private javax.swing.JPanel jpConnectionsList;
  private javax.swing.JPanel jpContent;
  private javax.swing.JPanel jpExport;
  private javax.swing.JScrollPane jspConnectionsList;
  private javax.swing.JToolBar jtbMain;
  private javax.swing.JTextField jtfExportFile;
  private javax.swing.JTextField jtfImportFile;
  private javax.swing.JTextField jtfPassword;
  private javax.swing.JTextField jtfUrl;
  private javax.swing.JTextField jtfUser;

  public MainFrm() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {

    jtbMain = new javax.swing.JToolBar();
    jbAddConnection = new javax.swing.JButton();
    jbRemoveConnection = new javax.swing.JButton();
    jpContent = new javax.swing.JPanel();
    jpConnectionsList = new ConnectionsListPanel();
    jspConnectionsList = new javax.swing.JScrollPane();
    jlConnectionsList = new javax.swing.JList();
    jpConnection = new ConnectionPanel();
    jlJdbcDriver = new javax.swing.JLabel();
    jcbDriver = new javax.swing.JComboBox();
    jlUrl = new javax.swing.JLabel();
    jtfUrl = new javax.swing.JTextField();
    jlUser = new javax.swing.JLabel();
    jlPassword = new javax.swing.JLabel();
    jtfUser = new javax.swing.JTextField();
    jtfPassword = new javax.swing.JTextField();
    jbTestConnection = new javax.swing.JButton();
    jpExport = new ExportChangelogPanel();
    jlExportFile = new javax.swing.JLabel();
    jtfExportFile = new javax.swing.JTextField();
    jbSelectExportFile = new javax.swing.JButton();
    jbExport = new javax.swing.JButton();
    jpImport = new ImportChangelogPanel();
    jlImportFile = new javax.swing.JLabel();
    jtfImportFile = new javax.swing.JTextField();
    jbSelectImportFile = new javax.swing.JButton();
    jbImport = new javax.swing.JButton();
    jmbMain = new javax.swing.JMenuBar();
    jmFile = new javax.swing.JMenu();
    jmiExit = new javax.swing.JMenuItem();
    jmService = new javax.swing.JMenu();
    jmiParameters = new javax.swing.JMenuItem();
    jmHelp = new javax.swing.JMenu();
    jmiAbout = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jtbMain.setRollover(true);

    jbAddConnection.setText("Добавить");
    jbAddConnection.setFocusable(false);
    jbAddConnection.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jbAddConnection.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jtbMain.add(jbAddConnection);

    jbRemoveConnection.setText("Удалить");
    jbRemoveConnection.setFocusable(false);
    jbRemoveConnection.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jbRemoveConnection.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jtbMain.add(jbRemoveConnection);

    jlConnectionsList.setModel(new ConnectionUnitModel());
    jlConnectionsList.setComponentPopupMenu(new ConnectionsPopupMenu());
    jspConnectionsList.setViewportView(jlConnectionsList);

    javax.swing.GroupLayout jpConnectionsListLayout = new javax.swing.GroupLayout(jpConnectionsList);
    jpConnectionsList.setLayout(jpConnectionsListLayout);
    jpConnectionsListLayout.setHorizontalGroup(
        jpConnectionsListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConnectionsListLayout.createSequentialGroup()
                .addComponent(jspConnectionsList, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
    );
    jpConnectionsListLayout.setVerticalGroup(
        jpConnectionsListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspConnectionsList)
    );

    jpConnection.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    jpConnection.setToolTipText("Параметры соединения");

    jlJdbcDriver.setText("JDBC-драйвер:");

    jcbDriver.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));

    jlUrl.setText("URL:");

    jlUser.setText("Пользователь:");

    jlPassword.setText("Пароль:");

    jbTestConnection.setText("Проверить");

    javax.swing.GroupLayout jpConnectionLayout = new javax.swing.GroupLayout(jpConnection);
    jpConnection.setLayout(jpConnectionLayout);
    jpConnectionLayout.setHorizontalGroup(
        jpConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConnectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpConnectionLayout.createSequentialGroup()
                        .addComponent(jlJdbcDriver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbDriver, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jtfUrl)
                    .addGroup(jpConnectionLayout.createSequentialGroup()
                        .addComponent(jlUrl)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpConnectionLayout.createSequentialGroup()
                        .addComponent(jlUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfPassword)
                            .addComponent(jbTestConnection, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))))
                .addContainerGap())
    );
    jpConnectionLayout.setVerticalGroup(
        jpConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConnectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlJdbcDriver)
                    .addComponent(jcbDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlUrl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlUser))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlPassword)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbTestConnection)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jpExport.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    jpExport.setToolTipText("Экспорт");

    jlExportFile.setText("Файл:");

    jbSelectExportFile.setText("...");

    jbExport.setText("Экспорт");

    javax.swing.GroupLayout jpExportLayout = new javax.swing.GroupLayout(jpExport);
    jpExport.setLayout(jpExportLayout);
    jpExportLayout.setHorizontalGroup(
        jpExportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpExportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlExportFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfExportFile, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSelectExportFile, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jbExport)
                .addContainerGap())
    );
    jpExportLayout.setVerticalGroup(
        jpExportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpExportLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpExportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlExportFile)
                    .addComponent(jtfExportFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSelectExportFile)
                    .addComponent(jbExport))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jpImport.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    jpImport.setToolTipText("Импорт");

    jlImportFile.setText("Файл:");

    jbSelectImportFile.setText("...");

    jbImport.setText("Импорт");

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jpImport);
    jpImport.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlImportFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfImportFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSelectImportFile, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jbImport, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
    );
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlImportFile)
                    .addComponent(jtfImportFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSelectImportFile)
                    .addComponent(jbImport))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jpContentLayout = new javax.swing.GroupLayout(jpContent);
    jpContent.setLayout(jpContentLayout);
    jpContentLayout.setHorizontalGroup(
        jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContentLayout.createSequentialGroup()
                .addComponent(jpConnectionsList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpConnection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpExport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpImport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
    );
    jpContentLayout.setVerticalGroup(
        jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpConnectionsList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpContentLayout.createSequentialGroup()
                .addComponent(jpConnection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpExport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpImport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 99, Short.MAX_VALUE))
    );

    jmFile.setText("Файл");

    jmiExit.setText("Выход");
    jmFile.add(jmiExit);

    jmbMain.add(jmFile);

    jmService.setText("Сервис");

    jmiParameters.setText("Параметры");
    jmService.add(jmiParameters);

    jmbMain.add(jmService);

    jmHelp.setText("Справка");

    jmiAbout.setText("О'б");
    jmHelp.add(jmiAbout);

    jmbMain.add(jmHelp);

    setJMenuBar(jmbMain);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtbMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtbMain, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

        /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MainFrm().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify


}
